version: '3.9'
services:
  mysql-contenedor:
    image: mysql:8.0
    container_name: mysql-contenedor
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev-mysql'
      MYSQL_USER: 'user1'
      MYSQL_PASSWORD: 'pw1'
      MYSQL_ROOT_PASSWORD: 'root1'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "root", "ping", "Globant123", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 10
  mongocontenedor:
    image: mongo
    container_name: mongocontenedor-series
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'series-dev-mongo'
      MONGO_INITDB_ROOT_USERNAME: 'user-series-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'password-series-mongo'
    ports:
      - 27018:27018
    expose:
      - 27018
    volumes:
      - ./mongo-init-series.js:/docker-entrypoint-initdb.d/mongo-init-series.js:ro
  mongocontenedor1:
    image: mongo
    container_name: mongocontenedor-catalog
    restart: always
    environment:
       MONGO_INITDB_DATABASE: 'catalog-dev-mongo'
       MONGO_INITDB_ROOT_USERNAME: 'user-catalogo-mongo'
       MONGO_INITDB_ROOT_PASSWORD: 'password-catalogo-mongo'
      ports:
          - 27017:27017
      expose:
            - 27017
      volumes:
          - ./mongo-init-series.js:/docker-entrypoint-initdb.d/mongo-init-catalog.js:ro
  zipkin-contenedor:
    image: openzipkin/zipkin-slim
    container_name: zipkin-contenedor
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    expose:
      - 9411
    depends_on:
      - storage-contenedor
  storage-contenedor:
    image: busybox:1.31.0
    container_name: storage-contenedor

  rabbitmq-contenedor:
    image: rabbitmq:3-management
    container_name: rabbitmq-contenedor
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
      - 5672